-- ===================================================================
-- PostgreSQL Schema Reference
-- ===================================================================
-- Purpose:
--   This file is the source-of-truth reference for the full PostgreSQL schema.
--   It contains exact table definitions, column types, constraints, and indexes.
--
-- Environment:
--   Local development:
--     - Spring runs directly from IntelliJ
--     - PostgreSQL runs on local machine
--     - Redis runs in Docker
--
--   Production:
--     - Spring, PostgreSQL, and Redis run in Docker on AWS EC2
--
-- Package Rule:
--   Database access follows the project package structure below.
--     application.port
--     infrastructure.persistence.repository
--     infrastructure.persistence.adapter
--
-- Rules:
--   - Read docs/database-context.md first for table roles and business rules.
--   - Use this file for exact schema validation.
--   - Do not infer exact schema details from summary docs alone.
--   - If schema-related docs conflict, this file takes precedence.
--   - When schema changes, related docs must also be updated.
--
-- Related Docs:
--   - README.md
--   - AGENTS.md
--   - docs/database-context.md
--   - docs/work-context.md
--
-- Note:
--   Replace the content below with the full current PostgreSQL schema.
-- ===================================================================

-- Paste full schema below this line.
CREATE TABLE language (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    english_name VARCHAR(50) NOT NULL
);

CREATE TABLE school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE school_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_school_translation_school
        FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT fk_school_translation_language
        FOREIGN KEY (lang_code) REFERENCES language(code),
    CONSTRAINT uk_school_translation_school_lang
        UNIQUE (school_id, lang_code)
);

CREATE TABLE cafeteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cafeteria_school
        FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT uk_cafeteria_school_name
        UNIQUE (school_id, name)
);

CREATE TABLE religious_food_restriction (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ingredient (
    code VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE allergy (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    allergy_group VARCHAR(20) NOT NULL,
    display_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE religious_food_restriction_ingredient (
    religious_food_restriction_code VARCHAR(30) NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (religious_food_restriction_code, ingredient_code),
    CONSTRAINT fk_rfri_restriction
        FOREIGN KEY (religious_food_restriction_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT fk_rfri_ingredient
        FOREIGN KEY (ingredient_code)
        REFERENCES ingredient(code)
);

CREATE TABLE country (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT,
    email VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    country_code VARCHAR(10),
    language_code VARCHAR(10) DEFAULT 'en',
    religious_code VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_users_school
        FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT fk_users_language
        FOREIGN KEY (language_code) REFERENCES language(code),
    CONSTRAINT fk_users_religious_code
        FOREIGN KEY (religious_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT uk_users_email
        UNIQUE (email),
    CONSTRAINT fk_users_country
        FOREIGN KEY (country_code) REFERENCES country(code)
);

CREATE TABLE user_allergy (
    user_id BIGINT NOT NULL,
    allergy_code VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, allergy_code),
    CONSTRAINT fk_user_allergy_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_allergy_allergy
        FOREIGN KEY (allergy_code) REFERENCES allergy(code)
);

CREATE TABLE meal_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT NOT NULL,
    meal_date DATE NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_schedule_cafeteria
        FOREIGN KEY (cafeteria_id) REFERENCES cafeteria(id),
    CONSTRAINT uk_meal_schedule
        UNIQUE (cafeteria_id, meal_date, meal_type)
);

CREATE TABLE menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    spicy_level BIGINT NOT NULL,
    ai_analysis_status VARCHAR(20) NOT NULL,
    latest_ai_analyzed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE meal_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_schedule_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    corner_name VARCHAR(100),
    display_order INT NOT NULL,
    ingredient_info_source_type VARCHAR(20) NOT NULL,
    ingredient_info_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_menu_meal_schedule
        FOREIGN KEY (meal_schedule_id) REFERENCES meal_schedule(id),
    CONSTRAINT fk_meal_menu_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT uk_meal_menu_display_order
        UNIQUE (meal_schedule_id, display_order)
);

CREATE TABLE menu_ai_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    reason TEXT,
    analyzed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_ai_analysis_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id)
);

CREATE TABLE menu_ai_analysis_ingredient (
    menu_ai_analysis_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    confidence NUMERIC(5,2),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (menu_ai_analysis_id, ingredient_code),
    CONSTRAINT fk_menu_ai_analysis_ingredient_analysis
        FOREIGN KEY (menu_ai_analysis_id)
        REFERENCES menu_ai_analysis(id),
    CONSTRAINT fk_menu_ai_analysis_ingredient_ingredient
        FOREIGN KEY (ingredient_code)
        REFERENCES ingredient(code)
);

CREATE TABLE menu_ai_analysis_allergy (
    menu_ai_analysis_id BIGINT NOT NULL,
    allergy_code VARCHAR(30) NOT NULL,
    confidence NUMERIC(5,2),
    reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (menu_ai_analysis_id, allergy_code),
    CONSTRAINT fk_menu_ai_analysis_allergy_analysis
        FOREIGN KEY (menu_ai_analysis_id)
        REFERENCES menu_ai_analysis(id),
    CONSTRAINT fk_menu_ai_analysis_allergy_allergy
        FOREIGN KEY (allergy_code)
        REFERENCES allergy(code)
);

CREATE TABLE meal_menu_confirmed_ingredient (
    meal_menu_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    confirmed_by_user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (meal_menu_id, ingredient_code),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_user
        FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id)
);

CREATE TABLE meal_menu_confirmation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_menu_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    target_type VARCHAR(30),
    ingredient_code VARCHAR(50),
    memo VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_menu_confirmation_history_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id),
    CONSTRAINT fk_meal_menu_confirmation_history_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_meal_menu_confirmation_history_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code)
);

CREATE TABLE menu_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_translation_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT fk_menu_translation_language
        FOREIGN KEY (lang_code) REFERENCES language(code),
    CONSTRAINT uk_menu_translation_menu_lang
        UNIQUE (menu_id, lang_code)
);

CREATE TABLE ingredient_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_code VARCHAR(50) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ingredient_translation_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code),
    CONSTRAINT fk_ingredient_translation_language
        FOREIGN KEY (lang_code) REFERENCES language(code),
    CONSTRAINT uk_ingredient_translation_ingredient_lang
        UNIQUE (ingredient_code, lang_code)
);

CREATE TABLE allergy_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allergy_code VARCHAR(30) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_allergy_translation_allergy
        FOREIGN KEY (allergy_code) REFERENCES allergy(code),
    CONSTRAINT fk_allergy_translation_language
        FOREIGN KEY (lang_code) REFERENCES language(code),
    CONSTRAINT uk_allergy_translation_allergy_lang
        UNIQUE (allergy_code, lang_code)
);

CREATE TABLE religious_food_restriction_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    religious_food_restriction_code VARCHAR(30) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_rfr_translation_restriction
        FOREIGN KEY (religious_food_restriction_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT fk_rfr_translation_language
        FOREIGN KEY (lang_code) REFERENCES language(code),
    CONSTRAINT uk_rfr_translation_restriction_lang
        UNIQUE (religious_food_restriction_code, lang_code)
);

CREATE TABLE meal_schedule_crawl_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_message VARCHAR(1000),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_schedule_crawl_history_cafeteria
        FOREIGN KEY (cafeteria_id) REFERENCES cafeteria(id)
);

CREATE TABLE meal_menu_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    meal_menu_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    content VARCHAR(1000) NOT NULL,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_meal_menu_review_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id),

    CONSTRAINT fk_meal_menu_review_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE meal_menu_review_like (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    PRIMARY KEY (review_id, user_id),

    CONSTRAINT fk_meal_menu_review_like_review
        FOREIGN KEY (review_id) REFERENCES meal_menu_review(id) ON DELETE CASCADE,

    CONSTRAINT fk_meal_menu_review_like_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE menu_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    cafeteria_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_menu_like_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT fk_menu_like_cafeteria
        FOREIGN KEY (cafeteria_id) REFERENCES cafeteria(id),

    CONSTRAINT fk_menu_like_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),

    CONSTRAINT uk_menu_like_user_target
        UNIQUE (user_id, cafeteria_id, menu_id)
);

CREATE TABLE menu_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    cafeteria_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    meal_menu_id BIGINT,
    meal_date DATE,
    content TEXT NOT NULL,
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_menu_review_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_review_cafeteria
        FOREIGN KEY (cafeteria_id) REFERENCES cafeteria(id),
    CONSTRAINT fk_menu_review_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT fk_menu_review_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id)
);

CREATE TABLE menu_review_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_menu_review_like_review
        FOREIGN KEY (review_id) REFERENCES menu_review(id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_review_like_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_menu_review_like_review_user
        UNIQUE (review_id, user_id)
);

CREATE TABLE menu_review_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_menu_review_comment_review
        FOREIGN KEY (review_id) REFERENCES menu_review(id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_review_comment_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_menu_ai_analysis_allergy_allergy_code
    ON menu_ai_analysis_allergy (allergy_code);

CREATE INDEX idx_cafeteria_school_id
    ON cafeteria (school_id);

CREATE INDEX idx_users_school_id
    ON users (school_id);

CREATE INDEX idx_users_language_code
    ON users (language_code);

CREATE INDEX idx_users_religious_code
    ON users (religious_code);

CREATE INDEX idx_meal_schedule_cafeteria_date
    ON meal_schedule (cafeteria_id, meal_date);

CREATE INDEX idx_meal_menu_menu_id
    ON meal_menu (menu_id);

CREATE INDEX idx_meal_menu_meal_schedule_id
    ON meal_menu (meal_schedule_id);

CREATE INDEX idx_meal_menu_source_status
    ON meal_menu (ingredient_info_source_type, ingredient_info_status);

CREATE INDEX idx_menu_ai_analysis_menu_id
    ON menu_ai_analysis (menu_id);

CREATE INDEX idx_menu_ai_analysis_menu_status_analyzed_at
    ON menu_ai_analysis (menu_id, status, analyzed_at);

CREATE INDEX idx_meal_menu_confirmed_ingredient_ingredient_code
    ON meal_menu_confirmed_ingredient (ingredient_code);

CREATE INDEX idx_user_allergy_user_id
    ON user_allergy (user_id);

CREATE INDEX idx_rfri_ingredient_code
    ON religious_food_restriction_ingredient (ingredient_code);

CREATE INDEX idx_school_translation_lang_code
    ON school_translation (lang_code);

CREATE INDEX idx_menu_translation_lang_code
    ON menu_translation (lang_code);

CREATE INDEX idx_ingredient_translation_lang_code
    ON ingredient_translation (lang_code);

CREATE INDEX idx_allergy_translation_lang_code
    ON allergy_translation (lang_code);

CREATE INDEX idx_rfr_translation_lang_code
    ON religious_food_restriction_translation (lang_code);

CREATE INDEX idx_meal_schedule_crawl_history_cafeteria_id
    ON meal_schedule_crawl_history (cafeteria_id);

CREATE INDEX idx_meal_schedule_crawl_history_started_at
    ON meal_schedule_crawl_history (started_at);

CREATE INDEX idx_meal_menu_review_meal_menu_id
    ON meal_menu_review (meal_menu_id);

CREATE INDEX idx_meal_menu_review_user_id
    ON meal_menu_review (user_id);

CREATE INDEX idx_meal_menu_review_created_at
    ON meal_menu_review (created_at);

CREATE INDEX idx_meal_menu_review_like_user_id
    ON meal_menu_review_like (user_id);

CREATE INDEX idx_menu_like_target
    ON menu_like (cafeteria_id, menu_id);

CREATE INDEX idx_menu_like_user
    ON menu_like (user_id);

CREATE INDEX idx_menu_review_target_created
    ON menu_review (cafeteria_id, menu_id, created_at DESC, id DESC);

CREATE INDEX idx_menu_review_user_created
    ON menu_review (user_id, created_at DESC);

CREATE INDEX idx_menu_review_meal_menu
    ON menu_review (meal_menu_id);

CREATE INDEX idx_menu_review_like_review
    ON menu_review_like (review_id);

CREATE INDEX idx_menu_review_like_user
    ON menu_review_like (user_id);

CREATE INDEX idx_menu_review_comment_review_created
    ON menu_review_comment (review_id, created_at ASC, id ASC);

CREATE INDEX idx_menu_review_comment_user_created
    ON menu_review_comment (user_id, created_at DESC);

CREATE INDEX idx_users_country_code
    ON users (country_code);

CREATE INDEX IF NOT EXISTS idx_allergy_group_display_order
    ON allergy (allergy_group, display_order);

INSERT INTO language (code, name, english_name) VALUES
('ko', '한국어', 'Korean'),
('en', '영어', 'English');

-- =========================================================
-- 1. religious_food_restriction
-- =========================================================
INSERT INTO religious_food_restriction (code, name, created_at) VALUES
('HALAL', '할랄', CURRENT_TIMESTAMP),
('HINDU', '힌두교', CURRENT_TIMESTAMP),
('VEGETARIAN', '베지테리언', CURRENT_TIMESTAMP),
('VEGAN', '비건', CURRENT_TIMESTAMP);

-- =========================================================
-- 2. religious_food_restriction_translation
-- =========================================================
INSERT INTO religious_food_restriction_translation (
    id,
    religious_food_restriction_code,
    lang_code,
    name,
    is_auto_translated,
    created_at,
    updated_at
) VALUES
(1, 'HALAL', 'ko', '할랄', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'HALAL', 'en', 'Halal', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3, 'HINDU', 'ko', '힌두교', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'HINDU', 'en', 'Hindu', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 'VEGETARIAN', 'ko', '베지테리언', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'VEGETARIAN', 'en', 'Vegetarian', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(7, 'VEGAN', 'ko', '비건', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'VEGAN', 'en', 'Vegan', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 3. ingredient
--    일단 종교/식단 기피 재료만 등록
-- =========================================================
INSERT INTO ingredient (code, name, created_at) VALUES
('PORK', '돼지고기', CURRENT_TIMESTAMP),
('LARD', '돼지기름', CURRENT_TIMESTAMP),
('PORK_BROTH', '돼지육수', CURRENT_TIMESTAMP),
('GELATIN', '젤라틴', CURRENT_TIMESTAMP),
('ALCOHOL', '알코올', CURRENT_TIMESTAMP),
('COOKING_WINE', '맛술', CURRENT_TIMESTAMP),

('BEEF', '소고기', CURRENT_TIMESTAMP),
('BEEF_BROTH', '소고기육수', CURRENT_TIMESTAMP),

('CHICKEN', '닭고기', CURRENT_TIMESTAMP),
('FISH', '생선', CURRENT_TIMESTAMP),
('SEAFOOD', '해산물', CURRENT_TIMESTAMP),
('SHELLFISH', '조개류', CURRENT_TIMESTAMP),
('SHRIMP', '새우', CURRENT_TIMESTAMP),
('CRAB', '게', CURRENT_TIMESTAMP),
('SQUID', '오징어', CURRENT_TIMESTAMP),
('OCTOPUS', '문어', CURRENT_TIMESTAMP),
('CLAM', '조개', CURRENT_TIMESTAMP),
('MUSSEL', '홍합', CURRENT_TIMESTAMP),
('ANCHOVY', '멸치', CURRENT_TIMESTAMP),

('EGG', '달걀', CURRENT_TIMESTAMP),
('MILK', '우유', CURRENT_TIMESTAMP),
('CHEESE', '치즈', CURRENT_TIMESTAMP),
('BUTTER', '버터', CURRENT_TIMESTAMP),
('YOGURT', '요거트', CURRENT_TIMESTAMP),

('ANIMAL_FAT', '동물성지방', CURRENT_TIMESTAMP),
('ANIMAL_STOCK', '동물성육수', CURRENT_TIMESTAMP),
('BONE_BROTH', '사골육수', CURRENT_TIMESTAMP),
('HONEY', '꿀', CURRENT_TIMESTAMP);

-- =========================================================
-- 4. ingredient_translation
-- =========================================================
INSERT INTO ingredient_translation (
    id,
    ingredient_code,
    lang_code,
    name,
    is_auto_translated,
    created_at,
    updated_at
) VALUES
(1, 'PORK', 'ko', '돼지고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'PORK', 'en', 'Pork', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3, 'LARD', 'ko', '돼지기름', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'LARD', 'en', 'Lard', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 'PORK_BROTH', 'ko', '돼지육수', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PORK_BROTH', 'en', 'Pork broth', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(7, 'GELATIN', 'ko', '젤라틴', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'GELATIN', 'en', 'Gelatin', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(9, 'ALCOHOL', 'ko', '알코올', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'ALCOHOL', 'en', 'Alcohol', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(11, 'COOKING_WINE', 'ko', '맛술', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'COOKING_WINE', 'en', 'Cooking wine', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(13, 'BEEF', 'ko', '소고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'BEEF', 'en', 'Beef', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(15, 'BEEF_BROTH', 'ko', '소고기육수', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'BEEF_BROTH', 'en', 'Beef broth', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(17, 'CHICKEN', 'ko', '닭고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'CHICKEN', 'en', 'Chicken', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(19, 'FISH', 'ko', '생선', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'FISH', 'en', 'Fish', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(21, 'SEAFOOD', 'ko', '해산물', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'SEAFOOD', 'en', 'Seafood', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(23, 'SHELLFISH', 'ko', '조개류', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'SHELLFISH', 'en', 'Shellfish', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(25, 'SHRIMP', 'ko', '새우', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'SHRIMP', 'en', 'Shrimp', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(27, 'CRAB', 'ko', '게', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'CRAB', 'en', 'Crab', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(29, 'SQUID', 'ko', '오징어', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'SQUID', 'en', 'Squid', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(31, 'OCTOPUS', 'ko', '문어', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 'OCTOPUS', 'en', 'Octopus', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(33, 'CLAM', 'ko', '조개', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'CLAM', 'en', 'Clam', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(35, 'MUSSEL', 'ko', '홍합', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 'MUSSEL', 'en', 'Mussel', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(37, 'ANCHOVY', 'ko', '멸치', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 'ANCHOVY', 'en', 'Anchovy', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(39, 'EGG', 'ko', '달걀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 'EGG', 'en', 'Egg', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(41, 'MILK', 'ko', '우유', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 'MILK', 'en', 'Milk', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(43, 'CHEESE', 'ko', '치즈', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 'CHEESE', 'en', 'Cheese', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(45, 'BUTTER', 'ko', '버터', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 'BUTTER', 'en', 'Butter', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(47, 'YOGURT', 'ko', '요거트', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 'YOGURT', 'en', 'Yogurt', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(49, 'ANIMAL_FAT', 'ko', '동물성지방', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 'ANIMAL_FAT', 'en', 'Animal fat', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(51, 'ANIMAL_STOCK', 'ko', '동물성육수', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 'ANIMAL_STOCK', 'en', 'Animal stock', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(53, 'BONE_BROTH', 'ko', '사골육수', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 'BONE_BROTH', 'en', 'Bone broth', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(55, 'HONEY', 'ko', '꿀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 'HONEY', 'en', 'Honey', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 5. religious_food_restriction_ingredient
-- =========================================================
INSERT INTO religious_food_restriction_ingredient (
    religious_food_restriction_code,
    ingredient_code,
    created_at
) VALUES
-- HALAL
('HALAL', 'PORK', CURRENT_TIMESTAMP),
('HALAL', 'LARD', CURRENT_TIMESTAMP),
('HALAL', 'PORK_BROTH', CURRENT_TIMESTAMP),
('HALAL', 'GELATIN', CURRENT_TIMESTAMP),
('HALAL', 'ALCOHOL', CURRENT_TIMESTAMP),
('HALAL', 'COOKING_WINE', CURRENT_TIMESTAMP),
('HALAL', 'ANIMAL_FAT', CURRENT_TIMESTAMP),

-- HINDU
('HINDU', 'BEEF', CURRENT_TIMESTAMP),
('HINDU', 'BEEF_BROTH', CURRENT_TIMESTAMP),
('HINDU', 'BONE_BROTH', CURRENT_TIMESTAMP),

-- VEGETARIAN
('VEGETARIAN', 'PORK', CURRENT_TIMESTAMP),
('VEGETARIAN', 'LARD', CURRENT_TIMESTAMP),
('VEGETARIAN', 'PORK_BROTH', CURRENT_TIMESTAMP),
('VEGETARIAN', 'BEEF', CURRENT_TIMESTAMP),
('VEGETARIAN', 'BEEF_BROTH', CURRENT_TIMESTAMP),
('VEGETARIAN', 'CHICKEN', CURRENT_TIMESTAMP),
('VEGETARIAN', 'FISH', CURRENT_TIMESTAMP),
('VEGETARIAN', 'SEAFOOD', CURRENT_TIMESTAMP),
('VEGETARIAN', 'SHELLFISH', CURRENT_TIMESTAMP),
('VEGETARIAN', 'SHRIMP', CURRENT_TIMESTAMP),
('VEGETARIAN', 'CRAB', CURRENT_TIMESTAMP),
('VEGETARIAN', 'SQUID', CURRENT_TIMESTAMP),
('VEGETARIAN', 'OCTOPUS', CURRENT_TIMESTAMP),
('VEGETARIAN', 'CLAM', CURRENT_TIMESTAMP),
('VEGETARIAN', 'MUSSEL', CURRENT_TIMESTAMP),
('VEGETARIAN', 'ANCHOVY', CURRENT_TIMESTAMP),
('VEGETARIAN', 'ANIMAL_FAT', CURRENT_TIMESTAMP),
('VEGETARIAN', 'ANIMAL_STOCK', CURRENT_TIMESTAMP),
('VEGETARIAN', 'BONE_BROTH', CURRENT_TIMESTAMP),
('VEGETARIAN', 'GELATIN', CURRENT_TIMESTAMP),

-- VEGAN
('VEGAN', 'PORK', CURRENT_TIMESTAMP),
('VEGAN', 'LARD', CURRENT_TIMESTAMP),
('VEGAN', 'PORK_BROTH', CURRENT_TIMESTAMP),
('VEGAN', 'BEEF', CURRENT_TIMESTAMP),
('VEGAN', 'BEEF_BROTH', CURRENT_TIMESTAMP),
('VEGAN', 'CHICKEN', CURRENT_TIMESTAMP),
('VEGAN', 'FISH', CURRENT_TIMESTAMP),
('VEGAN', 'SEAFOOD', CURRENT_TIMESTAMP),
('VEGAN', 'SHELLFISH', CURRENT_TIMESTAMP),
('VEGAN', 'SHRIMP', CURRENT_TIMESTAMP),
('VEGAN', 'CRAB', CURRENT_TIMESTAMP),
('VEGAN', 'SQUID', CURRENT_TIMESTAMP),
('VEGAN', 'OCTOPUS', CURRENT_TIMESTAMP),
('VEGAN', 'CLAM', CURRENT_TIMESTAMP),
('VEGAN', 'MUSSEL', CURRENT_TIMESTAMP),
('VEGAN', 'ANCHOVY', CURRENT_TIMESTAMP),
('VEGAN', 'EGG', CURRENT_TIMESTAMP),
('VEGAN', 'MILK', CURRENT_TIMESTAMP),
('VEGAN', 'CHEESE', CURRENT_TIMESTAMP),
('VEGAN', 'BUTTER', CURRENT_TIMESTAMP),
('VEGAN', 'YOGURT', CURRENT_TIMESTAMP),
('VEGAN', 'HONEY', CURRENT_TIMESTAMP),
('VEGAN', 'ANIMAL_FAT', CURRENT_TIMESTAMP),
('VEGAN', 'ANIMAL_STOCK', CURRENT_TIMESTAMP),
('VEGAN', 'BONE_BROTH', CURRENT_TIMESTAMP),
('VEGAN', 'GELATIN', CURRENT_TIMESTAMP);

-- =========================================================
-- 6. allergy
-- =========================================================
INSERT INTO allergy (
    code,
    name,
    allergy_group,
    display_order,
    created_at
)
VALUES
    -- seafood
    ('MACKEREL', '고등어', 'SEAFOOD', 1, CURRENT_TIMESTAMP),
    ('CRAB', '게', 'SEAFOOD', 2, CURRENT_TIMESTAMP),
    ('SHRIMP', '새우', 'SEAFOOD', 3, CURRENT_TIMESTAMP),
    ('SQUID', '오징어', 'SEAFOOD', 4, CURRENT_TIMESTAMP),
    ('SHELLFISH', '조개류', 'SEAFOOD', 5, CURRENT_TIMESTAMP),
    ('CLAM', '조개', 'SEAFOOD', 6, CURRENT_TIMESTAMP),
    ('MUSSEL', '홍합', 'SEAFOOD', 7, CURRENT_TIMESTAMP),
    ('OYSTER', '굴', 'SEAFOOD', 8, CURRENT_TIMESTAMP),
    ('LOBSTER', '랍스터', 'SEAFOOD', 9, CURRENT_TIMESTAMP),
    ('SCALLOP', '가리비', 'SEAFOOD', 10, CURRENT_TIMESTAMP),

    -- meat
    ('PORK', '돼지고기', 'MEAT', 11, CURRENT_TIMESTAMP),
    ('CHICKEN', '닭고기', 'MEAT', 12, CURRENT_TIMESTAMP),
    ('BEEF', '쇠고기', 'MEAT', 13, CURRENT_TIMESTAMP),

    -- dairy-eggs
    ('EGG', '난류', 'DAIRY_EGGS', 14, CURRENT_TIMESTAMP),
    ('MILK', '우유', 'DAIRY_EGGS', 15, CURRENT_TIMESTAMP),

    -- grains-beans-nuts
    ('PEANUT', '땅콩', 'GRAINS_BEANS_NUTS', 16, CURRENT_TIMESTAMP),
    ('SOYBEAN', '대두', 'GRAINS_BEANS_NUTS', 17, CURRENT_TIMESTAMP),
    ('WHEAT', '밀', 'GRAINS_BEANS_NUTS', 18, CURRENT_TIMESTAMP),
    ('BUCKWHEAT', '메밀', 'GRAINS_BEANS_NUTS', 19, CURRENT_TIMESTAMP),
    ('OATS', '귀리', 'GRAINS_BEANS_NUTS', 20, CURRENT_TIMESTAMP),
    ('RYE', '호밀', 'GRAINS_BEANS_NUTS', 21, CURRENT_TIMESTAMP),
    ('BARLEY', '보리', 'GRAINS_BEANS_NUTS', 22, CURRENT_TIMESTAMP),
    ('TREE_NUT', '견과류', 'GRAINS_BEANS_NUTS', 23, CURRENT_TIMESTAMP),
    ('WALNUT', '호두', 'GRAINS_BEANS_NUTS', 24, CURRENT_TIMESTAMP),
    ('ALMOND', '아몬드', 'GRAINS_BEANS_NUTS', 25, CURRENT_TIMESTAMP),
    ('HAZELNUT', '헤이즐넛', 'GRAINS_BEANS_NUTS', 26, CURRENT_TIMESTAMP),
    ('CASHEW', '캐슈너트', 'GRAINS_BEANS_NUTS', 27, CURRENT_TIMESTAMP),
    ('PISTACHIO', '피스타치오', 'GRAINS_BEANS_NUTS', 28, CURRENT_TIMESTAMP),
    ('PECAN', '피칸', 'GRAINS_BEANS_NUTS', 29, CURRENT_TIMESTAMP),
    ('BRAZIL_NUT', '브라질너트', 'GRAINS_BEANS_NUTS', 30, CURRENT_TIMESTAMP),
    ('MACADAMIA', '마카다미아', 'GRAINS_BEANS_NUTS', 31, CURRENT_TIMESTAMP),
    ('PINE_NUT', '잣', 'GRAINS_BEANS_NUTS', 32, CURRENT_TIMESTAMP),

    -- fruits
    ('PEACH', '복숭아', 'FRUITS', 33, CURRENT_TIMESTAMP),
    ('MANGO', '망고', 'FRUITS', 34, CURRENT_TIMESTAMP),
    ('AVOCADO', '아보카도', 'FRUITS', 35, CURRENT_TIMESTAMP),
    ('BANANA', '바나나', 'FRUITS', 36, CURRENT_TIMESTAMP),
    ('KIWI', '키위', 'FRUITS', 37, CURRENT_TIMESTAMP),

    -- vegetables
    ('TOMATO', '토마토', 'VEGETABLES', 38, CURRENT_TIMESTAMP),
    ('CELERY', '셀러리', 'VEGETABLES', 39, CURRENT_TIMESTAMP),
    ('MUSTARD', '머스타드', 'VEGETABLES', 40, CURRENT_TIMESTAMP),

    -- additives
    ('SULFITES', '아황산류', 'ADDITIVES', 41, CURRENT_TIMESTAMP),
    ('SESAME', '참깨', 'ADDITIVES', 42, CURRENT_TIMESTAMP),
    ('LUPIN', '루핀', 'ADDITIVES', 43, CURRENT_TIMESTAMP),

    -- other
    ('LATEX_RELATED', '라텍스 관련 식품', 'OTHER', 44, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    allergy_group = EXCLUDED.allergy_group,
    display_order = EXCLUDED.display_order;
-- =========================================================
-- 7. allergy_translation
-- =========================================================
INSERT INTO allergy_translation (
    allergy_code,
    lang_code,
    name,
    is_auto_translated,
    created_at,
    updated_at
)
VALUES
    ('MACKEREL', 'ko', '고등어', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MACKEREL', 'en', 'Mackerel', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('CRAB', 'ko', '게', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CRAB', 'en', 'Crab', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SHRIMP', 'ko', '새우', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SHRIMP', 'en', 'Shrimp', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SQUID', 'ko', '오징어', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SQUID', 'en', 'Squid', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SHELLFISH', 'ko', '조개류', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SHELLFISH', 'en', 'Shellfish', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('CLAM', 'ko', '조개', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CLAM', 'en', 'Clam', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('MUSSEL', 'ko', '홍합', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MUSSEL', 'en', 'Mussel', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('OYSTER', 'ko', '굴', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('OYSTER', 'en', 'Oyster', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('LOBSTER', 'ko', '랍스터', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('LOBSTER', 'en', 'Lobster', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SCALLOP', 'ko', '가리비', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SCALLOP', 'en', 'Scallop', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PORK', 'ko', '돼지고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PORK', 'en', 'Pork', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('CHICKEN', 'ko', '닭고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CHICKEN', 'en', 'Chicken', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('BEEF', 'ko', '쇠고기', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BEEF', 'en', 'Beef', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('EGG', 'ko', '난류', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EGG', 'en', 'Egg', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('MILK', 'ko', '우유', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MILK', 'en', 'Milk', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PEANUT', 'ko', '땅콩', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PEANUT', 'en', 'Peanut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SOYBEAN', 'ko', '대두', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SOYBEAN', 'en', 'Soybean', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('WHEAT', 'ko', '밀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WHEAT', 'en', 'Wheat', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('BUCKWHEAT', 'ko', '메밀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BUCKWHEAT', 'en', 'Buckwheat', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('OATS', 'ko', '귀리', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('OATS', 'en', 'Oats', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('RYE', 'ko', '호밀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RYE', 'en', 'Rye', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('BARLEY', 'ko', '보리', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BARLEY', 'en', 'Barley', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('TREE_NUT', 'ko', '견과류', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TREE_NUT', 'en', 'Tree Nut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('WALNUT', 'ko', '호두', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WALNUT', 'en', 'Walnut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('ALMOND', 'ko', '아몬드', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ALMOND', 'en', 'Almond', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('HAZELNUT', 'ko', '헤이즐넛', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('HAZELNUT', 'en', 'Hazelnut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('CASHEW', 'ko', '캐슈너트', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CASHEW', 'en', 'Cashew', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PISTACHIO', 'ko', '피스타치오', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PISTACHIO', 'en', 'Pistachio', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PECAN', 'ko', '피칸', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PECAN', 'en', 'Pecan', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('BRAZIL_NUT', 'ko', '브라질너트', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BRAZIL_NUT', 'en', 'Brazil Nut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('MACADAMIA', 'ko', '마카다미아', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MACADAMIA', 'en', 'Macadamia', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PINE_NUT', 'ko', '잣', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PINE_NUT', 'en', 'Pine Nut', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('PEACH', 'ko', '복숭아', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PEACH', 'en', 'Peach', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('MANGO', 'ko', '망고', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MANGO', 'en', 'Mango', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('AVOCADO', 'ko', '아보카도', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('AVOCADO', 'en', 'Avocado', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('BANANA', 'ko', '바나나', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BANANA', 'en', 'Banana', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('KIWI', 'ko', '키위', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('KIWI', 'en', 'Kiwi', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('TOMATO', 'ko', '토마토', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TOMATO', 'en', 'Tomato', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('CELERY', 'ko', '셀러리', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CELERY', 'en', 'Celery', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('MUSTARD', 'ko', '머스타드', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MUSTARD', 'en', 'Mustard', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SULFITES', 'ko', '아황산류', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SULFITES', 'en', 'Sulfites', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('SESAME', 'ko', '참깨', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SESAME', 'en', 'Sesame', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('LUPIN', 'ko', '루핀', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('LUPIN', 'en', 'Lupin', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('LATEX_RELATED', 'ko', '라텍스 관련 식품', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('LATEX_RELATED', 'en', 'Latex-related foods', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (allergy_code, lang_code) DO UPDATE
SET
    name = EXCLUDED.name,
    is_auto_translated = EXCLUDED.is_auto_translated,
    updated_at = EXCLUDED.updated_at;


INSERT INTO school (id, name, source_url, created_at)
VALUES (1, '금오공과대학교', 'https://kumoh.ac.kr', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    source_url = EXCLUDED.source_url;

INSERT INTO school_translation (
    id, school_id, lang_code, name, is_auto_translated, created_at, updated_at
) VALUES
(1, 1, 'ko', '금오공과대학교', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 'en', 'Kumoh National Institute of Technology', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (school_id, lang_code) DO UPDATE
SET
    name = EXCLUDED.name,
    is_auto_translated = EXCLUDED.is_auto_translated,
    updated_at = EXCLUDED.updated_at;

INSERT INTO cafeteria (
    school_id,
    name,
    created_at
)
VALUES
    (1, '일품식당', CURRENT_TIMESTAMP),
    (1, '정찬식당', CURRENT_TIMESTAMP),
    (1, '분식당', CURRENT_TIMESTAMP)
ON CONFLICT (school_id, name) DO NOTHING;

INSERT INTO country (code, name, created_at) VALUES
('KR', 'South Korea', CURRENT_TIMESTAMP),
('US', 'United States', CURRENT_TIMESTAMP),
('JP', 'Japan', CURRENT_TIMESTAMP),
('CN', 'China', CURRENT_TIMESTAMP),
('VN', 'Vietnam', CURRENT_TIMESTAMP),
('MN', 'Mongolia', CURRENT_TIMESTAMP),
('UZ', 'Uzbekistan', CURRENT_TIMESTAMP),
('ID', 'Indonesia', CURRENT_TIMESTAMP),
('TH', 'Thailand', CURRENT_TIMESTAMP),
('PH', 'Philippines', CURRENT_TIMESTAMP),
('MY', 'Malaysia', CURRENT_TIMESTAMP),
('IN', 'India', CURRENT_TIMESTAMP),
('NP', 'Nepal', CURRENT_TIMESTAMP),
('BD', 'Bangladesh', CURRENT_TIMESTAMP),
('PK', 'Pakistan', CURRENT_TIMESTAMP),
('LK', 'Sri Lanka', CURRENT_TIMESTAMP),
('RU', 'Russia', CURRENT_TIMESTAMP),
('KZ', 'Kazakhstan', CURRENT_TIMESTAMP),
('KG', 'Kyrgyzstan', CURRENT_TIMESTAMP),
('MM', 'Myanmar', CURRENT_TIMESTAMP),
('KH', 'Cambodia', CURRENT_TIMESTAMP),
('LA', 'Laos', CURRENT_TIMESTAMP),
('SG', 'Singapore', CURRENT_TIMESTAMP),
('TW', 'Taiwan', CURRENT_TIMESTAMP),
('HK', 'Hong Kong', CURRENT_TIMESTAMP),
('GB', 'United Kingdom', CURRENT_TIMESTAMP),
('FR', 'France', CURRENT_TIMESTAMP),
('DE', 'Germany', CURRENT_TIMESTAMP),
('CA', 'Canada', CURRENT_TIMESTAMP),
('AU', 'Australia', CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;
