-- ===================================================================
-- PostgreSQL Schema Reference
-- ===================================================================
-- Purpose:
--   This file is the source-of-truth reference for the full PostgreSQL schema.
--   It contains exact table definitions, column types, constraints, and indexes.
--
-- Environment:
--   Local development:
--     - Spring runs directly from IntelliJ
--     - PostgreSQL runs on local machine
--     - Redis runs in Docker
--
--   Production:
--     - Spring, PostgreSQL, and Redis run in Docker on AWS EC2
--
-- Package Rule:
--   Database access follows the project package structure below.
--     application.port
--     infrastructure.persistence.repository
--     infrastructure.persistence.adapter
--
-- Rules:
--   - Read docs/database-context.md first for table roles and business rules.
--   - Use this file for exact schema validation.
--   - Do not infer exact schema details from summary docs alone.
--   - If schema-related docs conflict, this file takes precedence.
--   - When schema changes, related docs must also be updated.
--
-- Related Docs:
--   - README.md
--   - AGENTS.md
--   - docs/database-context.md
--   - docs/work-context.md
--
-- Note:
--   Replace the content below with the full current PostgreSQL schema.
-- ===================================================================

-- Paste full schema below this line.
CREATE TABLE school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE cafeteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cafeteria_school
        FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT uk_cafeteria_school_name
        UNIQUE (school_id, name)
);

CREATE TABLE religious_food_restriction (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ingredient (
    code VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE religious_food_restriction_ingredient (
    religious_food_restriction_code VARCHAR(30) NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (religious_food_restriction_code, ingredient_code),
    CONSTRAINT fk_rfri_restriction
        FOREIGN KEY (religious_food_restriction_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT fk_rfri_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT,
    email VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    religious_code VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_users_school
        FOREIGN KEY (school_id) REFERENCES school(id),
    CONSTRAINT fk_users_religious_code
        FOREIGN KEY (religious_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT uk_users_email
        UNIQUE (email)
);

CREATE TABLE user_oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_oauth_accounts_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_user_oauth_accounts_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_user_oauth_accounts_user_provider
        UNIQUE (user_id, provider)
);

CREATE TABLE user_avoided_ingredient (
    user_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, ingredient_code),
    CONSTRAINT fk_user_avoided_ingredient_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_avoided_ingredient_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code)
);

CREATE TABLE user_allergy_ingredient (
    user_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, ingredient_code),
    CONSTRAINT fk_user_allergy_ingredient_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_allergy_ingredient_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code)
);

CREATE TABLE meal_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT NOT NULL,
    meal_date DATE NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_schedule_cafeteria
        FOREIGN KEY (cafeteria_id) REFERENCES cafeteria(id),
    CONSTRAINT uk_meal_schedule
        UNIQUE (cafeteria_id, meal_date, meal_type)
);

CREATE TABLE menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    ai_analysis_status VARCHAR(20) NOT NULL,
    latest_ai_analyzed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE meal_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_schedule_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    corner_name VARCHAR(100),
    display_order INT NOT NULL,
    ingredient_info_source_type VARCHAR(20) NOT NULL,
    ingredient_info_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_menu_meal_schedule
        FOREIGN KEY (meal_schedule_id) REFERENCES meal_schedule(id),
    CONSTRAINT fk_meal_menu_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT uk_meal_menu_display_order
        UNIQUE (meal_schedule_id, display_order)
);

CREATE TABLE menu_ai_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    raw_result TEXT,
    analyzed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_ai_analysis_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id)
);

CREATE TABLE menu_ai_analysis_ingredient (
    menu_ai_analysis_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    confidence NUMERIC(5,2),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (menu_ai_analysis_id, ingredient_code),
    CONSTRAINT fk_menu_ai_analysis_ingredient_analysis
        FOREIGN KEY (menu_ai_analysis_id)
        REFERENCES menu_ai_analysis(id),
    CONSTRAINT fk_menu_ai_analysis_ingredient_ingredient
        FOREIGN KEY (ingredient_code)
        REFERENCES ingredient(code)
);

CREATE TABLE meal_menu_confirmed_ingredient (
    meal_menu_id BIGINT NOT NULL,
    ingredient_code VARCHAR(50) NOT NULL,
    confirmed_by_user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (meal_menu_id, ingredient_code),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code),
    CONSTRAINT fk_meal_menu_confirmed_ingredient_user
        FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id)
);

CREATE TABLE meal_menu_confirmation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_menu_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    ingredient_code VARCHAR(50),
    memo VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_meal_menu_confirmation_history_meal_menu
        FOREIGN KEY (meal_menu_id) REFERENCES meal_menu(id),
    CONSTRAINT fk_meal_menu_confirmation_history_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_meal_menu_confirmation_history_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code)
);

CREATE TABLE menu_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_translation_menu
        FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT uk_menu_translation_menu_lang
        UNIQUE (menu_id, lang_code)
);

CREATE TABLE ingredient_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_code VARCHAR(50) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ingredient_translation_ingredient
        FOREIGN KEY (ingredient_code) REFERENCES ingredient(code),
    CONSTRAINT uk_ingredient_translation_ingredient_lang
        UNIQUE (ingredient_code, lang_code)
);

CREATE TABLE religious_food_restriction_translation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    religious_food_restriction_code VARCHAR(30) NOT NULL,
    lang_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_auto_translated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_rfr_translation_restriction
        FOREIGN KEY (religious_food_restriction_code)
        REFERENCES religious_food_restriction(code),
    CONSTRAINT uk_rfr_translation_restriction_lang
        UNIQUE (religious_food_restriction_code, lang_code)
);

CREATE INDEX idx_menu_translation_lang_code
    ON menu_translation (lang_code);

CREATE INDEX idx_ingredient_translation_lang_code
    ON ingredient_translation (lang_code);

CREATE INDEX idx_rfr_translation_lang_code
    ON religious_food_restriction_translation (lang_code);

CREATE INDEX idx_cafeteria_school_id
    ON cafeteria (school_id);

CREATE INDEX idx_users_school_id
    ON users (school_id);

CREATE INDEX idx_users_religious_code
    ON users (religious_code);

CREATE INDEX idx_meal_schedule_cafeteria_date
    ON meal_schedule (cafeteria_id, meal_date);

CREATE INDEX idx_meal_menu_menu_id
    ON meal_menu (menu_id);

CREATE INDEX idx_meal_menu_meal_schedule_id
    ON meal_menu (meal_schedule_id);

CREATE INDEX idx_meal_menu_source_status
    ON meal_menu (ingredient_info_source_type, ingredient_info_status);

CREATE INDEX idx_menu_ai_analysis_menu_id
    ON menu_ai_analysis (menu_id);

CREATE INDEX idx_menu_ai_analysis_menu_status_analyzed_at
    ON menu_ai_analysis (menu_id, status, analyzed_at);

CREATE INDEX idx_meal_menu_confirmed_ingredient_ingredient_code
    ON meal_menu_confirmed_ingredient (ingredient_code);

CREATE INDEX idx_user_allergy_ingredient_user_id
    ON user_allergy_ingredient (user_id);

CREATE INDEX idx_user_avoided_ingredient_user_id
    ON user_avoided_ingredient (user_id);